name = "ZfpCompression"
uuid = "43441a71-1662-41c6-b8ea-40ed1525242b"
authors = ["Milan K <milankloewer@gmx.de> and contributors"]
version = "0.1.0"

[deps]
zfp_jll = "007be453-5351-5f08-b8c7-bf95923b8de2"

[compat]
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
