name = "Zfp"
uuid = "260ef742-b1f7-4398-8462-503aa05aec9c"
authors = ["Milan K <milankloewer@gmx.de> and contributors"]
version = "0.1.0"

[deps]
zfp_jll = "007be453-5351-5f08-b8c7-bf95923b8de2"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
